# Replace this by config.yaml in same location.
discopig:
  DISCORD_GUILD: [NameOfGuildGoesHere]
  DISCORD_TOKEN: [BotTokenGoesHere]

  CMD_PREFIX: '!'
  CATEGORY: PRINCESS
  LOBBY: gamelobby
  PLAYER_ROLE: GamePlayer
  MAX_GAMES: 10
